updateChecker: true
disabledCommandMessage: "&4[Server]: &fThis command is disabled for this world."

blacklist: true

plugins:
  Example:
    - PutWorldInThisListForDisableThisPluginOnWorld
    - world